openapi: 3.0.0
info:
  title: accounts
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /accounts/login:
    post:
      summary: ''
      operationId: post-accounts-login
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples:
                eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIyNmZiNTg2Ni0yNTE0LTQ3M2MtYTQyMy0xNzU1YjAxYTdkNDciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwibmJmIjoxNjE1NDg1NzEwLCJleHAiOjE2MTYwOTA1MTAsImlzcyI6IkZNSVdlYlNpdGVNYWluQVBJIiwiYXVkIjoiVGVzdEs1ZGllbmNlIn0.dYPCQl33NHlgb43um7OXAhcZQpLSX16jtE9uDeSpMqU:
                  value: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
  /accounts/register:
    post:
      summary: ''
      operationId: post-accounts-register
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              examples:
                eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIyNmZiNTg2Ni0yNTE0LTQ3M2MtYTQyMy0xNzU1YjAxYTdkNDciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwibmJmIjoxNjE1NDg1NzEwLCJleHAiOjE2MTYwOTA1MTAsImlzcyI6IkZNSVdlYlNpdGVNYWluQVBJIiwiYXVkIjoiVGVzdEs1ZGllbmNlIn0.dYPCQl33NHlgb43um7OXAhcZQpLSX16jtE9uDeSpMqU: {}
        '400':
          description: Bad Request
        '409':
          description: Conflict - Email уже занят
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                Full Name:
                  type: string
  /accounts/get_account:
    parameters: []
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  FullName:
                    type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      operationId: get-accounts-accountId
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer {token}'
components:
  schemas: {}
