openapi: 3.0.0
info:
  title: news
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /posts/add:
    post:
      summary: ''
      operationId: post-news-add
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
        '403':
          description: Forbidden
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer {token}'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Title:
                  type: string
                Content:
                  type: string
    parameters: []
  /posts:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Title:
                      type: string
                    Content:
                      type: string
                    Date:
                      type: string
        '401':
          description: Unauthorized
      operationId: get-news
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer {token}'
    parameters: []
  '/posts/{postId}':
    parameters:
      - schema:
          type: string
        name: postId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Title:
                    type: string
                  Content:
                    type: string
                  Date:
                    type: string
        '401':
          description: Unauthorized
      operationId: get-news-postId
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: 'Bearer {token}'
components:
  schemas: {}
